"""Join tasks + location mapping into data.js for the browser app."""
import json
import locations
import parse_list

OUT = 'data.js'


def main():
    tasks = json.load(open(parse_list.JSON_OUT))
    meta = locations.load()

    missing = sorted({t[k] for t in tasks for k in ('noticeBoard', 'from', 'to')} - set(meta))
    if missing:
        raise SystemExit(f'{locations.PATH} has no entry for: {missing}')

    with open(OUT, 'w') as f:
        f.write('// Generated by build.py - edit locations.tsv or port_tasks.list, then `make data`.\n')
        f.write(f'window.PORT_TASKS = {json.dumps(tasks)};\n')
        f.write(f'window.PORT_LOCATIONS = {json.dumps(meta, sort_keys=True)};\n')

    regions = sorted({v['region'] for v in meta.values()})
    oceans = sorted({o for v in meta.values() for o in v['oceans']})
    print(f'{OUT}: {len(tasks)} tasks, {len(meta)} locations, '
          f'{len(regions)} regions {regions}, {len(oceans)} oceans')


if __name__ == '__main__':
    main()
