"""Join tasks + location mapping into data.js for the browser app."""
import json
import locations
import mapdata
import parse_list

OUT = 'src/generated.js'


def map_info():
    """Tile grid + URL template the map viewer needs, from map_config.json."""
    cfg = mapdata.config()
    b = mapdata.bounds(cfg)
    return {
        'origin': b['origin'],
        'size': b['size'],
        'tilePx': mapdata.TILE_PX,
        'zooms': {str(z): g for z, g in b['zooms'].items()},
        'localUrl': mapdata.TILE_DIR + '/{z}/{x}_{y}.png',
        # used only when a tile is missing from tiles/ (run `make tiles`)
        'remoteUrl': mapdata.tile_url(cfg, '{z}', '{x}', '{y}'),
    }


def main():
    tasks = json.load(open(parse_list.JSON_OUT))
    meta = locations.load()

    missing = sorted({t[k] for t in tasks for k in ('noticeBoard', 'from', 'to')} - set(meta))
    if missing:
        raise SystemExit(f'{locations.PATH} has no entry for: {missing}')

    with open(OUT, 'w') as f:
        f.write('// Generated by build.py - edit locations.tsv or port_tasks.list, then `make data`.\n')
        f.write(f'export const TASKS = {json.dumps(tasks)};\n')
        f.write(f'export const LOCATIONS = {json.dumps(meta, sort_keys=True)};\n')
        f.write(f'export const MAP_META = {json.dumps(map_info())};\n')

    coords = sum(1 for v in meta.values() if v.get('coords'))
    regions = sorted({v['region'] for v in meta.values()})
    oceans = sorted({o for v in meta.values() for o in v['oceans']})
    print(f'{OUT}: {len(tasks)} tasks, {len(meta)} locations, '
          f'{len(regions)} regions, {len(oceans)} oceans, {coords} mapped')


if __name__ == '__main__':
    main()
