"""Fold tables into web/js/generated.js, the browser app's only data source."""
import json

from .paths import GENERATED_JS as OUT
from .paths import TILE_URL_DIR
from .tables import locations, tasks
from .tiles import grid


def map_info():
    """Tile grid + URL template the map viewer needs, from map_config.json."""
    cfg = grid.config()
    b = grid.bounds(cfg)
    return {
        'origin': b['origin'],
        'size': b['size'],
        'tilePx': grid.TILE_PX,
        'zooms': {str(z): g for z, g in b['zooms'].items()},
        'localUrl': TILE_URL_DIR + '/{z}/{x}_{y}.png',
        # used only when a tile is missing from web/tiles (run `make tiles`)
        'remoteUrl': grid.tile_url(cfg, '{z}', '{x}', '{y}'),
    }


def main():
    task_rows = json.load(open(tasks.JSON_OUT))
    meta = locations.load()

    missing = sorted({t[k] for t in task_rows for k in ('noticeBoard', 'from', 'to')} - set(meta))
    if missing:
        raise SystemExit(f'{locations.PATH} has no entry for: {missing}')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('// Generated by porttasks.generate - edit tables, then `make data`.\n')
        f.write(f'export const TASKS = {json.dumps(task_rows)};\n')
        f.write(f'export const LOCATIONS = {json.dumps(meta, sort_keys=True)};\n')
        f.write(f'export const MAP_META = {json.dumps(map_info())};\n')

    coords = sum(1 for v in meta.values() if v.get('coords'))
    regions = sorted({v['region'] for v in meta.values()})
    oceans = sorted({o for v in meta.values() for o in v['oceans']})
    print(f'{OUT}: {len(task_rows)} tasks, {len(meta)} locations, '
          f'{len(regions)} regions, {len(oceans)} oceans, {coords} mapped')


if __name__ == '__main__':
    main()
